### ISSUE TITLE
No Output from OTX Logs

### ISSUE THREAD

**Issue by b14ckyy** [stronnag/fl2xui#1]
When loading OTX logs, no output file is created. The same logs work with flightlog2kml though but not with fl2xui. 

![image](https://user-images.githubusercontent.com/33039058/156933420-cca5062c-4ee3-4986-a2be-55b03e996c98.png)
Sample Log: 
[Talon_250G-2022-01-15.csv](https://github.com/stronnag/fl2xui/files/8193074/Talon_250G-2022-01-15.csv)

**Comment by stronnag** [comment]
Huum ... from fl2xui. 

![talon-1](https://user-images.githubusercontent.com/158229/156933903-ea132fd9-01e7-4c56-b33b-26178c2135a2.png)
![talon-2](https://user-images.githubusercontent.com/158229/156933906-6c4b1f6d-0122-42b0-abf1-1db73c8db2d1.png)

Can you provide the mission (by PM if it's sensitive) ?
Or I'll have to try on Windows.

**Comment by b14ckyy** [comment]
I'll send you another mission and log as I don't have this mission file anymore, by DM.

**Comment by stronnag** [comment]
Oh dear, this is embarrassing ....
![Screenshot-36](https://user-images.githubusercontent.com/158229/156934511-755b830a-89f1-42dc-93ec-b9ca97c9b87e.png)

Files are smaller than on Linux, as I don't have extrude set by default in win11.

**Comment by stronnag** [comment]
> I'll send you another mission and log as I don't have this mission file anymore, by DM.

OK, and you don't have some invalid / weird output directory? (rather than the default of `Documents`).

**Comment by b14ckyy** [comment]
> > I'll send you another mission and log as I don't have this mission file anymore, by DM.
> 
> OK, and you don't have some invalid / weird output directory? (rather than the default of `Documents`).

No just Desktop. So a 100% user folder. If I manually set the outout folder and confirm it, then it works. Evne in the same folder as before.

**Comment by stronnag** [comment]
if `flightlog2kml` can't write the file, it will display an error, so it seems like Windows is doing something bizarre under the hood. 
To avoid user confusion, the next release of `flightlog2kml` will show where it's saving the file, thusly:
```
Flight   : 2022-01-15 15:14:39
Log      : Talon_250G-2022-01-15.csv / 1
Altitude : 82.8 m at 07:33
Speed    : 17.9 m/s at 10:30
Range    : 378 m at 04:19
Current  : 6.7 A at 03:00
Distance : 7451 m
Duration : 12:20
Output   : C:\Users\win11\Documents\Talon_250G-2022-01-15.1.kmz
```
