### ISSUE TITLE
No "datetime" header, probably blackbox_decode too old or broken on MacOS

### ISSUE THREAD

**Issue by mattcave** [stronnag/fl2xui#3]
Fresh build/install from source on MacOS

When processing a log I get the following error.

> No "datetime" header, probably blackbox_decode too old or broken

Blackbox_decode is recent.

> Blackbox flight log decoder by Nicholas Sherlock (Apr  3 2022 13:16:20)

**Other info**
OS is MacOS 12.3.1
fl2x binaries came from the release page as tar.gz (ie not built from source)
CSV file created by blackbox_decode has the following columns
`loopIteration, time (us), axisRate[0], axisRate[1], axisRate[2], axisP[0], axisP[1], axisP[2], axisI[0], axisI[1], axisI[2], axisD[0], axisD[1], axisD[2], fwAltP, fwAltI, fwAltD, fwAltOut, fwPosP, fwPosI, fwPosD, fwPosOut, rcData[0], rcData[1], rcData[2], rcData[3], rcCommand[0], rcCommand[1], rcCommand[2], rcCommand[3], vbat, amperage, BaroAlt (cm), rssi, gyroADC[0], gyroADC[1], gyroADC[2], accSmooth[0], accSmooth[1], accSmooth[2], attitude[0], attitude[1], attitude[2], motor[0], motor[1], servo[0], servo[1], servo[2], servo[3], servo[4], servo[5], servo[6], servo[7], servo[8], servo[9], servo[10], servo[11], servo[12], servo[13], servo[14], servo[15], navState, navFlags, navEPH, navEPV, navPos[0], navPos[1], navPos[2], navVel[0], navVel[1], navVel[2], navAcc[0], navAcc[1], navAcc[2], navTgtVel[0], navTgtVel[1], navTgtVel[2], navTgtPos[0], navTgtPos[1], navTgtPos[2], navSurf[0], flightModeFlags (flags), stateFlags (flags), failsafePhase (flags), rxSignalReceived, rxFlightChannelsValid, hwHealthStatus, powerSupplyImpedance, sagCompensatedVBat, wind[0], wind[1], wind[2], IMUTemperature, baroTemperature, sens0Temp, sens1Temp, sens2Temp, sens3Temp, sens4Temp, sens5Temp, sens6Temp, sens7Temp, escRPM, escTemperature`

**Comment by stronnag** [comment]
It is likely  that there is an older `blackbox_decode` on the PATH.
What is the output of:
* `which blackbox_decode` 
* `blackbox_decode --help`

If the result of the latter shows your `blackbox_decode` is older than the required version `0.4.4`  or  running `blackbox_decode --datetime --merge-gps LOG.TXT` gives an error, then, as per error message, you do not have a sufficiently new version of `blackbox_decode` available.

You can find a suitably recent version [on tne INAV github](https://github.com/iNavFlight/blackbox-tools/releases/tag/v4.0.1).

**Comment by mattcave** [comment]
Resolved, thank you. Problem traced to me using the latest, most up-to-date version of blackbox tools from _cleanflight_, not iNav. #facepalm 

Added confusion came from blackbox_decode --help reporting the compile date, not the code commit / release date. And, even less helpful, blackbox_decode --version doesn't report *anything* at all.

**Comment by stronnag** [comment]
At least (when the maintainer remembers to set it), inav `blackbox_decode` provides `--version`.
However, it would be useful if it also announced that it was the inav specific version. Let  me fix that for the next (inav 5.0) release.

**Comment by stronnag** [comment]
Note also that you can specify the full path to `blackbox_decode` in the [flightlog2kml configuration file](https://github.com/stronnag/bbl2kml/wiki/Sample-Config-file) , so in order to differentiate between INAV / βF variants, rename the inav version to `inav_blackbox_decode` and set the value in the configuration file.

```
   "blackbox-decode" : "inav_blackbox_decode",
```
