### ISSUE TITLE
Unable to deselect Mission in UI

### ISSUE THREAD

**Issue by mattcave** [stronnag/fl2xui#4]
This is a minor UX issue; I selected a mission, then realized I didn't actually want to include the mission in the KMZ file. Currently I don't think it's possible to clear the mission file in the UI without a restart. I can choose to hide the mission layer in Google Earth later so it's not a big deal, but it would be handy to just have an [x] button or whatever to clear the mission field in the fl2xui interface.

**Comment by stronnag** [comment]
It is possible, it's just an editable text field; select & delete.

**Comment by mattcave** [comment]
I tried that but it definitely won't let me. This might be a Mac-specific bug. When I select that field and hit delete I get the Mac OS error chime and the field does not clear.

**Comment by stronnag** [comment]
Works OK in my (somewhat ancient) MacOS VM.

**Comment by stronnag** [comment]
OTOH, you didn't bother to tell me which version you're running ....

**Comment by mattcave** [comment]
Reproducible on a new build from source on Ventura / Mac OS 13.1, FWIW.

**Comment by mattcave** [comment]
> OTOH, you didn't bother to tell me which version you're running ....

Cos I didn't initially realize it might be OS specific

**Comment by stronnag** [comment]
Which version of fl2xui?

**Comment by mattcave** [comment]
Ha, sorry!

git status
> On branch master
> Your branch is up to date with 'origin/master'.

git rev-parse --short HEAD
> 3090238

So that's v.1.1.0 I believe?

**Comment by stronnag** [comment]
`fl2xui --version` is the easiest way
and that commit is not even close to the current version (which made the mission field editable)

**Comment by mattcave** [comment]
You're correct, the version I'm actually running is only 1.0.2. Thanks for spotting my error.

**Comment by stronnag** [comment]
Which was almost the last GTK+-3.0 version. The later versions are GTK4, so there are changed dependencies.https://stronnag.github.io/fl2xui/#macos_1

**Comment by mattcave** [comment]
Trying to build latest version...    the first step completes OK, and then I get an error on the second step...

> matt@Matts-Mac-mini fl2xui % meson build --buildtype=release --strip --prefix=~/.local
> The Meson build system
> Version: 1.0.1
> Source dir: /Users/matt/Code/Personal/fl2xui
> Build dir: /Users/matt/Code/Personal/fl2xui/build
> Build type: native build
> Project name: fl2xui
> Project version: 1.1.0
> C compiler for the host machine: cc (clang 14.0.0 "Apple clang version 14.0.0 (clang-1400.0.29.202)")
> C linker for the host machine: cc ld64 820.1
> Vala compiler for the host machine: valac (valac 0.56.4)
> Host machine cpu family: aarch64
> Host machine cpu: aarch64
> Configuring fl2xui-config.h using configuration
> Fallback to subproject blueprint-compiler which provides program blueprint-compiler
> Cloning into 'blueprint-compiler'...
> remote: Enumerating objects: 217, done.
> remote: Counting objects: 100% (217/217), done.
> remote: Compressing objects: 100% (165/165), done.
> remote: Total 217 (delta 25), reused 163 (delta 16), pack-reused 0
> Receiving objects: 100% (217/217), 88.50 KiB | 974.00 KiB/s, done.
> Resolving deltas: 100% (25/25), done.
> 
> Executing subproject blueprint-compiler 
> 
> blueprint-compiler| Project name: blueprint-compiler
> blueprint-compiler| Project version: 0.2.0
> blueprint-compiler| Program python3 found: YES (/opt/homebrew/bin/python3)
> blueprint-compiler| Configuring blueprint-compiler.pc using configuration
> blueprint-compiler| Configuring blueprint-compiler using configuration
> blueprint-compiler| Program blueprint-compiler.py found: YES (/Users/matt/Code/Personal/fl2xui/subprojects/blueprint-compiler/blueprint-compiler.py)
> blueprint-compiler| Build targets in project: 0
> blueprint-compiler| Subproject blueprint-compiler finished.
> 
> Program blueprint-compiler.py found: YES (overridden)
> Program touch found: YES (/usr/bin/touch)
> Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
> Program glib-compile-resources found: YES (/opt/homebrew/bin/glib-compile-resources)
> Found pkg-config: /opt/homebrew/bin/pkg-config (0.29.2)
> Run-time dependency gtk4 found: YES 4.10.0
> Run-time dependency gio-2.0 found: YES 2.74.6
> Run-time dependency json-glib-1.0 found: YES 1.6.6
> Library posix found: YES
> Program gtk4-update-icon-cache found: YES (/opt/homebrew/bin/gtk4-update-icon-cache)
> Build targets in project: 5
> 
> fl2xui 1.1.0
> 
>   Subprojects
>     blueprint-compiler: YES
> 
>   User defined options
>     buildtype         : release
>     prefix            : ~/.local
>     strip             : True
> 
> Found ninja-1.11.1 at /opt/homebrew/bin/ninja

All looks OK, and then...

> matt@Matts-Mac-mini fl2xui % meson install -C build
> ninja: Entering directory `/Users/matt/Code/Personal/fl2xui/build'
> [1/11] Generating data/blueprints with a custom command
> **FAILED**: data/fl2xui.ui 
> /Users/matt/Code/Personal/fl2xui/subprojects/blueprint-compiler/blueprint-compiler.py batch-compile data ../data ../data/fl2xui.blp
> error: Could not find GTK 4 introspection files. Is gobject-introspection installed?
> at ../data/fl2xui.blp line 1 column 11:
>    1 |using Gtk 4.0;
>      |          ^
> 
> [2/11] Compiling Vala source ../src/fl2xui.vala ../src/prefs.vala ../src/process.vala ../src/combo.vala ../src/scrollview.vala
> ../src/fl2xui.vala:254.3-254.17: warning: `Gtk.DropTarget.on_drop' has been deprecated since vala-0.58. Use DropTarget.drop
>   254 | 		droptgt.on_drop.connect((tgt, value, x, y) => {
>       | 		^~~~~~~~~~~~~~~                                
> Compilation succeeded - 1 warning(s)
> ninja: build stopped: subcommand failed.
> Could not rebuild /Users/matt/Code/Personal/fl2xui/build

Would you prefer this in a separate issue?

**Comment by stronnag** [comment]
You're missing the `brew`  package `gobject-introspection` . I'll update the build guide.

**Comment by mattcave** [comment]
I actually already tried that but I still get the same error.

**Comment by stronnag** [comment]
Huum. Does `find /usr/local/share -iname \*.gir | grep 4.0` list at least the following?
```
/usr/local/share/gir-1.0/Gdk-4.0.gir
/usr/local/share/gir-1.0/Gtk-4.0.gir
```

Does this help ? 

```
export XDG_DATA_DIRS=$XDG_DATA_DIRS:/usr/local/share
```

I don't have to do that, but perhaps it is necessary to log out / in after installing the introspection package to get `brew` to set things up (speculation).

**Comment by mattcave** [comment]
On my system there's nothing at all in /usr/local/share except man pages

gobject-introspection installs all its files in /opt/homebrew/Cellar 

> matt@Matts-Mac-mini fl2xui % brew ls gobject-introspection
> ==> Downloading https://formulae.brew.sh/api/cask.jws.json
> ######################################################################## 100.0%
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/bin/g-ir-annotation-tool
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/bin/g-ir-compiler
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/bin/g-ir-generate
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/bin/g-ir-inspect
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/bin/g-ir-scanner
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/include/gobject-introspection-1.0/ (22 files)
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/lib/libgirepository-1.0.1.dylib
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/lib/girepository-1.0/ (18 files)
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/lib/gobject-introspection/ (93 files)
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/lib/pkgconfig/ (2 files)
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/lib/libgirepository-1.0.dylib
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/share/aclocal/introspection.m4
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/share/gir-1.0/ (19 files)
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/share/gobject-introspection-1.0/ (19 files)
> /opt/homebrew/Cellar/gobject-introspection/1.74.0/share/man/ (4 files)

**Comment by stronnag** [comment]
FIne. MacOS is not longer supported.

**Comment by mattcave** [comment]
:-)

**Comment by mattcave** [comment]
Was able to fix the build error with...

> export XDG_DATA_DIRS=$XDG_DATA_DIRS:/opt/homebrew/share

**Comment by mattcave** [comment]
And confirming that the UI element now works as you described; I can delete the text in the Mission box successfully.
