### ISSUE TITLE
Sampling interval is not saved

### ISSUE THREAD

**Issue by mattcave** [stronnag/fl2xui#5]
When clicking Save settings, the Sampling Interval value is not saved in the $HOME/.config/fl2x/config.json config file

**Comment by stronnag** [comment]
This is by design as the sampling interval is  input file dependent (this is documented https://github.com/stronnag/bbl2kml/wiki/Sample-Config-file)

**Comment by mattcave** [comment]
I don't understand how it is input file dependent. The Sampling Interval value is in seconds, correct? The input file (ie blackbox file) could contain data at a higher or lower frequency than that (e.g. 20 values per second or 1 value every 10 seconds), but the KMZ generated by fl2xui should include one "blob" per sampling interval (assuming the input file has data at least that often).

**Comment by stronnag** [comment]
If I have a 3 hour BBL, I probably only want every say 10 seconds to keep the KMZ managable; it a 2 minute BBL, perhaps every 0.1s.

**Comment by mattcave** [comment]
OK, that logic makes sense.
