### ISSUE TITLE
old version of blueprint, fails build on MacOS Sonoma

### ISSUE THREAD

**Issue by silicongarage** [stronnag/fl2xui#6]
<img width="876" alt="image" src="https://github.com/user-attachments/assets/1f3f8cd7-621b-42f3-b3d9-82060fa6582a">

I  replaced the subprojects directory with that from mwptools (development) branch.
fl2xui now builds on runs MacOS

**Comment by stronnag** [comment]
It just needs the *.wrap file updating to the latest version

**Comment by stronnag** [comment]
Fixed in 3e30219
